#!/bin/bash

export CLASSPATH=/usr/local/share/bbs

echo "Waiting for port 1099 to release..."
while [ -n "`netstat -tulnap 2>/dev/null | grep 1099`" ]; do
    : # do nothing 
done
sleep 1

echo "Loading RMI registry..."
( screen -d -m rmiregistry & )
sleep 1

echo "Waiting for port 1099 to get acquired..."
while [ -z "`netstat -tulnap 2>/dev/null | grep 1099`" ]; do
    : # do nothing 
done
sleep 1
